name: Release

on:
  push:
    tags:
      - "v*"

env:
  SCCACHE_GHA_ENABLED: "true"
  SCCACHE_CACHE_SIZE: 2G
  RUSTC_WRAPPER: "sccache"

jobs:
  build-win:
    runs-on: windows-latest

    env:
      FILE_NAME: target/release/preprintd-win-latest.zip

    steps:
      - uses: actions/checkout@v6

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9

      - run: cargo build --release --quiet --locked
      - run: sccache --show-stats || true

      - name: Compress binary
        run: |
          powershell -Command "Compress-Archive -Path target/release/preprintd.exe -DestinationPath $env:FILE_NAME"

      - name: Upload compressed binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.FILE_NAME }}
          tag: ${{ github.ref }}
          overwrite: true

  build-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      FILE_NAME: target/release/preprintd-${{ matrix.os }}.tar.gz

    steps:
      - uses: actions/checkout@v6

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9

      - run: cargo build --release --quiet --locked
      - run: sccache --show-stats || true

      - name: Compress binary
        run: tar -czf ${{ env.FILE_NAME }} -C target/release preprintd

      - name: Upload compressed binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.FILE_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
